name: Build VSIX Extension
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Bundle with esbuild
        run: |
          npx esbuild ./src/extension.ts \
            --bundle \
            --outfile=out/extension.js \
            --external:vscode \
            --external:vscode-languageclient \
            --platform=node \
            --format=cjs

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package VSIX
        run: vsce package --out ./wml-lsp.vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: wml-lsp.vsix
          path: wml-lsp.vsix

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          name: Latest Build
          files: ./wml-lsp.vsix
